var allGlovesArray = [];
allGlovesArray.push({id:1, cats: [2,3], name: 'The Original® Glove', link: '/gloveThumbs/_sized/1.jpg'});
allGlovesArray.push({id:2, cats: [2,3], name: 'FastFit® Glove', link: '/gloveThumbs/_sized/2.jpg'});
allGlovesArray.push({id:3, cats: [2,3], name: 'M-Pact® Glove', link: '/gloveThumbs/_sized/3.jpg'});
allGlovesArray.push({id:4, cats: [2,3], name: 'M-Pact® 2 Glove', link: '/gloveThumbs/_sized/4.jpg'});
allGlovesArray.push({id:5, cats: [2,3], name: 'M-Pact® Fingerless', link: '/gloveThumbs/_sized/5.jpg'});
allGlovesArray.push({id:6, cats: [3], name: 'The Original® Plus Glove', link: '/gloveThumbs/_sized/6.jpg'});
allGlovesArray.push({id:7, cats: [2,3], name: 'The Original® Vent Glove', link: '/gloveThumbs/_sized/7.jpg'});
allGlovesArray.push({id:8, cats: [2,3], name: 'The Original® 0.5 Glove', link: '/gloveThumbs/_sized/8.jpg'});
allGlovesArray.push({id:9, cats: [2,3], name: 'The Original® Grip Glove', link: '/gloveThumbs/_sized/9.jpg'});
allGlovesArray.push({id:10, cats: [3], name: 'The Original® Glove Light', link: '/gloveThumbs/_sized/10.jpg'});
allGlovesArray.push({id:11, cats: [3], name: 'The Original® Womens Glove', link: '/gloveThumbs/_sized/11.jpg'});
allGlovesArray.push({id:12, cats: [2], name: 'M-Pact® 3 Glove', link: '/gloveThumbs/_sized/12.jpg'});
allGlovesArray.push({id:13, cats: [2,3], name: 'MRT 0.5 M-Pact™ Glove', link: '/gloveThumbs/_sized/13.jpg'});
allGlovesArray.push({id:14, cats: [2], name: 'Team Issue: Carbon X® Level 1 Glove', link: '/gloveThumbs/_sized/14.jpg'});
allGlovesArray.push({id:15, cats: [2], name: 'Team Issue: Carbon X® Level 5 Glove', link: '/gloveThumbs/_sized/15.jpg'});
allGlovesArray.push({id:16, cats: [2], name: 'Team Issue: Carbon X® Level 10 Glove', link: '/gloveThumbs/_sized/16.jpg'});
allGlovesArray.push({id:17, cats: [2], name: 'Fabricator Glove', link: '/gloveThumbs/_sized/17.jpg'});
allGlovesArray.push({id:18, cats: [2], name: 'Happy Hour Glove', link: '/gloveThumbs/_sized/18.jpg'});
allGlovesArray.push({id:19, cats: [4,7], name: 'Utility Glove', link: '/gloveThumbs/_sized/19.jpg'});
allGlovesArray.push({id:20, cats: [4], name: 'Padded Palm Glove', link: '/gloveThumbs/_sized/20.jpg'});
allGlovesArray.push({id:21, cats: [4], name: 'Impact Pro Glove', link: '/gloveThumbs/_sized/21.jpg'});
allGlovesArray.push({id:22, cats: [7], name: 'Womens Utility Glove', link: '/gloveThumbs/_sized/22.jpg'});
allGlovesArray.push({id:23, cats: [4,8], name: 'CG Utility Glove', link: '/gloveThumbs/_sized/23.jpg'});
allGlovesArray.push({id:24, cats: [4,8], name: 'CG Padded Palm Glove', link: '/gloveThumbs/_sized/24.jpg'});
allGlovesArray.push({id:25, cats: [4,8], name: 'CG Framer Glove', link: '/gloveThumbs/_sized/25.jpg'});
allGlovesArray.push({id:26, cats: [4,8], name: 'CG Impact Pro Glove', link: '/gloveThumbs/_sized/26.jpg'});
allGlovesArray.push({id:27, cats: [4,8], name: 'CG Heavy Duty Glove', link: '/gloveThumbs/_sized/27.jpg'});
allGlovesArray.push({id:28, cats: [6], name: 'The Original® Covert Glove', link: '/gloveThumbs/_sized/28.jpg'});
allGlovesArray.push({id:29, cats: [6], name: 'The Original® Woodland Camo Glove', link: '/gloveThumbs/_sized/29.jpg'});
allGlovesArray.push({id:30, cats: [6], name: 'The Original Coyote Glove', link: '/gloveThumbs/_sized/30.jpg'});
allGlovesArray.push({id:31, cats: [6], name: 'M-Pact® Covert Glove', link: '/gloveThumbs/_sized/31.jpg'});
allGlovesArray.push({id:32, cats: [6], name: 'M-Pact® Woodland Camo Glove', link: '/gloveThumbs/_sized/32.jpg'});
allGlovesArray.push({id:33, cats: [6], name: 'M-Pact® Coyote Glove', link: '/gloveThumbs/_sized/33.jpg'});
allGlovesArray.push({id:34, cats: [6], name: 'M-Pact® 2 Covert Glove', link: '/gloveThumbs/_sized/34.jpg'});
allGlovesArray.push({id:35, cats: [6], name: 'Performance Leather Driver Glove', link: '/gloveThumbs/_sized/35.jpg'});
allGlovesArray.push({id:36, cats: [5], name: 'The Safety FastFit®', link: '/gloveThumbs/_sized/36.jpg'});
allGlovesArray.push({id:37, cats: [5], name: 'The Safety Original®', link: '/gloveThumbs/_sized/37.jpg'});
allGlovesArray.push({id:38, cats: [5], name: 'The Safety M-Pact®', link: '/gloveThumbs/_sized/38.jpg'});
allGlovesArray.push({id:39, cats: [5], name: 'The Safety M-Pact® 2', link: '/gloveThumbs/_sized/39.jpg'});
allGlovesArray.push({id:40, cats: [5], name: 'The Safety M-Pact® ORHD', link: '/gloveThumbs/_sized/40.jpg'});
allGlovesArray.push({id:41, cats: [9], name: 'Cold Weather Fleece Utility Glove', link: '/gloveThumbs/_sized/41.jpg'});
allGlovesArray.push({id:42, cats: [9], name: 'Cold Weather Wind Resistant Glove', link: '/gloveThumbs/_sized/42.jpg'});
allGlovesArray.push({id:43, cats: [9], name: 'Original® Insulated Glove', link: '/gloveThumbs/_sized/43.jpg'});
allGlovesArray.push({id:44, cats: [9], name: 'FastFit® Insulated Glove', link: '/gloveThumbs/_sized/44.jpg'});
allGlovesArray.push({id:45, cats: [4], name: 'CG4x Utility', link: '/gloveThumbs/_sized/45.jpg'});
allGlovesArray.push({id:46, cats: [4], name: 'CG4x Framer', link: '/gloveThumbs/_sized/46.jpg'});
allGlovesArray.push({id:47, cats: [4], name: 'CG4x Padded Palm', link: '/gloveThumbs/_sized/47.jpg'});
allGlovesArray.push({id:48, cats: [4], name: 'CG4x Impact Pro', link: '/gloveThumbs/_sized/48.jpg'});
allGlovesArray.push({id:49, cats: [9], name: 'Shop Apron', link: '/gloveThumbs/_sized/49.jpg'});
allGlovesArray.push({id:50, cats: [9], name: 'Heat Sleeves', link: '/gloveThumbs/_sized/50.jpg'});
allGlovesArray.push({id:51, cats: [9], name: 'Radio Belt', link: '/gloveThumbs/_sized/51.jpg'});
allGlovesArray.push({id:52, cats: [9], name: 'Mechanix Knee Pad', link: '/gloveThumbs/_sized/52.jpg'});
allGlovesArray.push({id:53, cats: [9], name: 'Team Issue Knee Pad', link: '/gloveThumbs/_sized/53.jpg'});
allGlovesArray.push({id:54, cats: [9], name: 'Travel Bag', link: '/gloveThumbs/_sized/54.jpg'});
allGlovesArray.push({id:55, cats: [9], name: 'Back Pack', link: '/gloveThumbs/_sized/55.jpg'});
allGlovesArray.push({id:56, cats: [9], name: 'Lanyard', link: '/gloveThumbs/_sized/56.jpg'});
allGlovesArray.push({id:57, cats: [9], name: 'Stickers', link: '/gloveThumbs/_sized/57.jpg'});
allGlovesArray.push({id:58, cats: [9], name: 'Vinyl Track Banners', link: '/gloveThumbs/_sized/58.jpg'});
allGlovesArray.push({id:59, cats: [9], name: 'Umbrella', link: '/gloveThumbs/_sized/59.jpg'});
allGlovesArray.push({id:60, cats: [9], name: 'Raincoat', link: '/gloveThumbs/_sized/60.jpg'});
allGlovesArray.push({id:61, cats: [9], name: 'Logo Hat', link: '/gloveThumbs/_sized/61.jpg'});
allGlovesArray.push({id:62, cats: [9], name: 'Scatter Hat', link: '/gloveThumbs/_sized/62.jpg'});
allGlovesArray.push({id:63, cats: [6], name: 'TAA FastFit® Glove', link: '/gloveThumbs/_sized/63.jpg'});
allGlovesArray.push({id:64, cats: [6], name: 'TAA Original® Glove', link: '/gloveThumbs/_sized/64.jpg'});
allGlovesArray.push({id:65, cats: [6], name: 'TAA M-Pact® Glove', link: '/gloveThumbs/_sized/65.jpg'});
allGlovesArray.push({id:66, cats: [6], name: 'TAA M-Pact® 2 Glove', link: '/gloveThumbs/_sized/66.jpg'});
allGlovesArray.push({id:67, cats: [6], name: 'TAA M-Pact® 3 Glove', link: '/gloveThumbs/_sized/67.jpg'});
allGlovesArray.push({id:68, cats: [9], name: '20 Year T-Shirt', link: '/gloveThumbs/_sized/68.jpg'});