var allGlovesArray = [];
allGlovesArray.push({id:1, cats: [2,3], name: 'The Original® Glove', link: '/gloveThumbs/1.jpg'});
allGlovesArray.push({id:2, cats: [2,3], name: 'FastFit® Glove', link: '/gloveThumbs/2.jpg'});
allGlovesArray.push({id:3, cats: [2,3], name: 'M-Pact® Glove', link: '/gloveThumbs/3.jpg'});
allGlovesArray.push({id:4, cats: [2,3], name: 'M-Pact® 2 Glove', link: '/gloveThumbs/4.jpg'});
allGlovesArray.push({id:5, cats: [2,3], name: 'M-Pact® Fingerless', link: '/gloveThumbs/5.jpg'});
allGlovesArray.push({id:6, cats: [3], name: 'The Original® Plus Glove', link: '/gloveThumbs/6.jpg'});
allGlovesArray.push({id:7, cats: [2,3], name: 'The Original® Vent Glove', link: '/gloveThumbs/7.jpg'});
allGlovesArray.push({id:8, cats: [2,3], name: 'The Original® 0.5 Glove', link: '/gloveThumbs/8.jpg'});
allGlovesArray.push({id:9, cats: [2,3], name: 'The Original® Grip Glove', link: '/gloveThumbs/9.jpg'});
allGlovesArray.push({id:10, cats: [3], name: 'The Original® Glove Light', link: '/gloveThumbs/10.jpg'});
allGlovesArray.push({id:11, cats: [3], name: 'The Original® Womens Glove', link: '/gloveThumbs/11.jpg'});
allGlovesArray.push({id:12, cats: [2], name: 'M-Pact® 3 Glove', link: '/gloveThumbs/12.jpg'});
allGlovesArray.push({id:13, cats: [2,3], name: 'MRT 0.5 M-Pact™ Glove', link: '/gloveThumbs/13.jpg'});
allGlovesArray.push({id:14, cats: [2], name: 'Team Issue: Carbon X® Level 1 Glove', link: '/gloveThumbs/14.jpg'});
allGlovesArray.push({id:15, cats: [2], name: 'Team Issue: Carbon X® Level 5 Glove', link: '/gloveThumbs/15.jpg'});
allGlovesArray.push({id:16, cats: [2], name: 'Team Issue: Carbon X® Level 10 Glove', link: '/gloveThumbs/16.jpg'});
allGlovesArray.push({id:17, cats: [2], name: 'Fabricator Glove', link: '/gloveThumbs/17.jpg'});
allGlovesArray.push({id:18, cats: [2], name: 'Happy Hour Glove', link: '/gloveThumbs/18.jpg'});
allGlovesArray.push({id:19, cats: [4,7], name: 'Utility Glove', link: '/gloveThumbs/19.jpg'});
allGlovesArray.push({id:20, cats: [4], name: 'Padded Palm Glove', link: '/gloveThumbs/20.jpg'});
allGlovesArray.push({id:21, cats: [4], name: 'Impact Pro Glove', link: '/gloveThumbs/21.jpg'});
allGlovesArray.push({id:22, cats: [7], name: 'Womens Utility Glove', link: '/gloveThumbs/22.jpg'});
allGlovesArray.push({id:23, cats: [4,8], name: 'CG Utility Glove', link: '/gloveThumbs/23.jpg'});
allGlovesArray.push({id:24, cats: [4,8], name: 'CG Padded Palm Glove', link: '/gloveThumbs/24.jpg'});
allGlovesArray.push({id:25, cats: [4,8], name: 'CG Framer Glove', link: '/gloveThumbs/25.jpg'});
allGlovesArray.push({id:26, cats: [4,8], name: 'CG Impact Pro Glove', link: '/gloveThumbs/26.jpg'});
allGlovesArray.push({id:27, cats: [4,8], name: 'CG Heavy Duty Glove', link: '/gloveThumbs/27.jpg'});
allGlovesArray.push({id:28, cats: [6], name: 'The Original® Covert Glove', link: '/gloveThumbs/28.jpg'});
allGlovesArray.push({id:29, cats: [6], name: 'The Original® Woodland Camo Glove', link: '/gloveThumbs/29.jpg'});
allGlovesArray.push({id:30, cats: [6], name: 'The Original Coyote Glove', link: '/gloveThumbs/30.jpg'});
allGlovesArray.push({id:31, cats: [6], name: 'M-Pact® Covert Glove', link: '/gloveThumbs/31.jpg'});
allGlovesArray.push({id:32, cats: [6], name: 'M-Pact® Woodland Camo Glove', link: '/gloveThumbs/32.jpg'});
allGlovesArray.push({id:33, cats: [6], name: 'M-Pact® Coyote Glove', link: '/gloveThumbs/33.jpg'});
allGlovesArray.push({id:34, cats: [6], name: 'M-Pact® 2 Covert Glove', link: '/gloveThumbs/34.jpg'});
allGlovesArray.push({id:35, cats: [6], name: 'Performance Leather Driver Glove', link: '/gloveThumbs/35.jpg'});
allGlovesArray.push({id:36, cats: [5], name: 'The Safety FastFit®', link: '/gloveThumbs/36.jpg'});
allGlovesArray.push({id:37, cats: [5], name: 'The Safety Original®', link: '/gloveThumbs/37.jpg'});
allGlovesArray.push({id:38, cats: [5], name: 'The Safety M-Pact®', link: '/gloveThumbs/38.jpg'});
allGlovesArray.push({id:39, cats: [5], name: 'The Safety M-Pact® 2', link: '/gloveThumbs/39.jpg'});
allGlovesArray.push({id:40, cats: [5], name: 'The Safety M-Pact® ORHD', link: '/gloveThumbs/40.jpg'});
allGlovesArray.push({id:41, cats: [9], name: 'Cold Weather Fleece Utility Glove', link: '/gloveThumbs/41.jpg'});
allGlovesArray.push({id:42, cats: [9], name: 'Cold Weather Wind Resistant Glove', link: '/gloveThumbs/42.jpg'});
allGlovesArray.push({id:43, cats: [9], name: 'Original® Insulated Glove', link: '/gloveThumbs/43.jpg'});
allGlovesArray.push({id:44, cats: [9], name: 'FastFit® Insulated Glove', link: '/gloveThumbs/44.jpg'});
allGlovesArray.push({id:45, cats: [4], name: 'CG4x Utility', link: '/gloveThumbs/45.jpg'});
allGlovesArray.push({id:46, cats: [4], name: 'CG4x Framer', link: '/gloveThumbs/46.jpg'});
allGlovesArray.push({id:47, cats: [4], name: 'CG4x Padded Palm', link: '/gloveThumbs/47.jpg'});
allGlovesArray.push({id:48, cats: [4], name: 'CG4x Impact Pro', link: '/gloveThumbs/48.jpg'});
allGlovesArray.push({id:49, cats: [9], name: 'Shop Apron', link: '/gloveThumbs/49.jpg'});
allGlovesArray.push({id:50, cats: [9], name: 'Heat Sleeves', link: '/gloveThumbs/50.jpg'});
allGlovesArray.push({id:51, cats: [9], name: 'Radio Belt', link: '/gloveThumbs/51.jpg'});
allGlovesArray.push({id:52, cats: [9], name: 'Mechanix Knee Pad', link: '/gloveThumbs/52.jpg'});
allGlovesArray.push({id:53, cats: [9], name: 'Team Issue Knee Pad', link: '/gloveThumbs/53.jpg'});
allGlovesArray.push({id:54, cats: [9], name: 'Travel Bag', link: '/gloveThumbs/54.jpg'});
allGlovesArray.push({id:55, cats: [9], name: 'Back Pack', link: '/gloveThumbs/55.jpg'});
allGlovesArray.push({id:56, cats: [9], name: 'Lanyard', link: '/gloveThumbs/56.jpg'});
allGlovesArray.push({id:57, cats: [9], name: 'Stickers', link: '/gloveThumbs/57.jpg'});
allGlovesArray.push({id:58, cats: [9], name: 'Vinyl Track Banners', link: '/gloveThumbs/58.jpg'});
allGlovesArray.push({id:59, cats: [9], name: 'Umbrella', link: '/gloveThumbs/59.jpg'});
allGlovesArray.push({id:60, cats: [9], name: 'Raincoat', link: '/gloveThumbs/60.jpg'});
allGlovesArray.push({id:61, cats: [9], name: 'Logo Hat', link: '/gloveThumbs/61.jpg'});
allGlovesArray.push({id:62, cats: [9], name: 'Scatter Hat', link: '/gloveThumbs/62.jpg'});
allGlovesArray.push({id:63, cats: [6], name: 'TAA FastFit® Glove', link: '/gloveThumbs/63.jpg'});
allGlovesArray.push({id:64, cats: [6], name: 'TAA Original® Glove', link: '/gloveThumbs/64.jpg'});
allGlovesArray.push({id:65, cats: [6], name: 'TAA M-Pact® Glove', link: '/gloveThumbs/65.jpg'});
allGlovesArray.push({id:66, cats: [6], name: 'TAA M-Pact® 2 Glove', link: '/gloveThumbs/66.jpg'});
allGlovesArray.push({id:67, cats: [6], name: 'TAA M-Pact® 3 Glove', link: '/gloveThumbs/67.jpg'});
allGlovesArray.push({id:68, cats: [9], name: '20 Year T-Shirt', link: '/gloveThumbs/68.jpg'});