var allGlovesArray = {'gloves':[
{id:'1', cat:[{catID:'2', catID:'3'}], name:'The Original® Glove', link: '/gloveThumbs/1.jpg'},
{id:'2', cat:[{catID:'2', catID:'3'}], name:'FastFit® Glove', link: '/gloveThumbs/2.jpg'},
{id:'3', cat:[{catID:'2', catID:'3'}], name:'M-Pact® Glove', link: '/gloveThumbs/3.jpg'},
{id:'4', cat:[{catID:'2', catID:'3'}], name:'M-Pact® 2 Glove', link: '/gloveThumbs/4.jpg'},
{id:'5', cat:[{catID:'2', catID:'3'}], name:'M-Pact® Fingerless', link: '/gloveThumbs/5.jpg'},
{id:'6', cat:[{catID:'3'}], name:'The Original® Plus Glove', link: '/gloveThumbs/6.jpg'},
{id:'7', cat:[{catID:'2', catID:'3'}], name:'The Original® Vent Glove', link: '/gloveThumbs/7.jpg'},
{id:'8', cat:[{catID:'2', catID:'3'}], name:'The Original® 0.5 Glove', link: '/gloveThumbs/8.jpg'},
{id:'9', cat:[{catID:'2', catID:'3'}], name:'The Original® Grip Glove', link: '/gloveThumbs/9.jpg'},
{id:'10', cat:[{catID:'3'}], name:'The Original® Glove Light', link: '/gloveThumbs/10.jpg'},
{id:'11', cat:[{catID:'3'}], name:'The Original® Womens Glove', link: '/gloveThumbs/11.jpg'},
{id:'12', cat:[{catID:'2'}], name:'M-Pact® 3 Glove', link: '/gloveThumbs/12.jpg'},
{id:'13', cat:[{catID:'2', catID:'3'}], name:'MRT 0.5 M-Pact™ Glove', link: '/gloveThumbs/13.jpg'},
{id:'14', cat:[{catID:'2'}], name:'Team Issue: Carbon X® Level 1 Glove', link: '/gloveThumbs/14.jpg'},
{id:'15', cat:[{catID:'2'}], name:'Team Issue: Carbon X® Level 5 Glove', link: '/gloveThumbs/15.jpg'},
{id:'16', cat:[{catID:'2'}], name:'Team Issue: Carbon X® Level 10 Glove', link: '/gloveThumbs/16.jpg'},
{id:'17', cat:[{catID:'2'}], name:'Fabricator Glove', link: '/gloveThumbs/17.jpg'},
{id:'18', cat:[{catID:'2'}], name:'Happy Hour Glove', link: '/gloveThumbs/18.jpg'},
{id:'19', cat:[{catID:'4', catID:'7'}], name:'Utility Glove', link: '/gloveThumbs/19.jpg'},
{id:'20', cat:[{catID:'4'}], name:'Padded Palm Glove', link: '/gloveThumbs/20.jpg'},
{id:'21', cat:[{catID:'4'}], name:'Impact Pro Glove', link: '/gloveThumbs/21.jpg'},
{id:'22', cat:[{catID:'7'}], name:'Womens Utility Glove', link: '/gloveThumbs/22.jpg'},
{id:'23', cat:[{catID:'4', catID:'8'}], name:'CG Utility Glove', link: '/gloveThumbs/23.jpg'},
{id:'24', cat:[{catID:'4', catID:'8'}], name:'CG Padded Palm Glove', link: '/gloveThumbs/24.jpg'},
{id:'25', cat:[{catID:'4', catID:'8'}], name:'CG Framer Glove', link: '/gloveThumbs/25.jpg'},
{id:'26', cat:[{catID:'4', catID:'8'}], name:'CG Impact Pro Glove', link: '/gloveThumbs/26.jpg'},
{id:'27', cat:[{catID:'4', catID:'8'}], name:'CG Heavy Duty Glove', link: '/gloveThumbs/27.jpg'},
{id:'28', cat:[{catID:'6'}], name:'The Original® Covert Glove', link: '/gloveThumbs/28.jpg'},
{id:'29', cat:[{catID:'6'}], name:'The Original® Woodland Camo Glove', link: '/gloveThumbs/29.jpg'},
{id:'30', cat:[{catID:'6'}], name:'The Original Coyote Glove', link: '/gloveThumbs/30.jpg'},
{id:'31', cat:[{catID:'6'}], name:'M-Pact® Covert Glove', link: '/gloveThumbs/31.jpg'},
{id:'32', cat:[{catID:'6'}], name:'M-Pact® Woodland Camo Glove', link: '/gloveThumbs/32.jpg'},
{id:'33', cat:[{catID:'6'}], name:'M-Pact® Coyote Glove', link: '/gloveThumbs/33.jpg'},
{id:'34', cat:[{catID:'6'}], name:'M-Pact® 2 Covert Glove', link: '/gloveThumbs/34.jpg'},
{id:'35', cat:[{catID:'6'}], name:'Performance Leather Driver Glove', link: '/gloveThumbs/35.jpg'},
{id:'36', cat:[{catID:'5'}], name:'The Safety FastFit®', link: '/gloveThumbs/36.jpg'},
{id:'37', cat:[{catID:'5'}], name:'The Safety Original®', link: '/gloveThumbs/37.jpg'},
{id:'38', cat:[{catID:'5'}], name:'The Safety M-Pact®', link: '/gloveThumbs/38.jpg'},
{id:'39', cat:[{catID:'5'}], name:'The Safety M-Pact® 2', link: '/gloveThumbs/39.jpg'},
{id:'40', cat:[{catID:'5'}], name:'The Safety M-Pact® ORHD', link: '/gloveThumbs/40.jpg'},
{id:'41', cat:[{catID:'9'}], name:'Cold Weather Fleece Utility Glove', link: '/gloveThumbs/41.jpg'},
{id:'42', cat:[{catID:'9'}], name:'Cold Weather Wind Resistant Glove', link: '/gloveThumbs/42.jpg'},
{id:'43', cat:[{catID:'9'}], name:'Original® Insulated Glove', link: '/gloveThumbs/43.jpg'},
{id:'44', cat:[{catID:'9'}], name:'FastFit® Insulated Glove', link: '/gloveThumbs/44.jpg'},
{id:'45', cat:[{catID:'4'}], name:'CG4x Utility', link: '/gloveThumbs/45.jpg'},
{id:'46', cat:[{catID:'4'}], name:'CG4x Framer', link: '/gloveThumbs/46.jpg'},
{id:'47', cat:[{catID:'4'}], name:'CG4x Padded Palm', link: '/gloveThumbs/47.jpg'},
{id:'48', cat:[{catID:'4'}], name:'CG4x Impact Pro', link: '/gloveThumbs/48.jpg'},
{id:'49', cat:[{catID:'9'}], name:'Shop Apron', link: '/gloveThumbs/49.jpg'},
{id:'50', cat:[{catID:'9'}], name:'Heat Sleeves', link: '/gloveThumbs/50.jpg'},
{id:'51', cat:[{catID:'9'}], name:'Radio Belt', link: '/gloveThumbs/51.jpg'},
{id:'52', cat:[{catID:'9'}], name:'Mechanix Knee Pad', link: '/gloveThumbs/52.jpg'},
{id:'53', cat:[{catID:'9'}], name:'Team Issue Knee Pad', link: '/gloveThumbs/53.jpg'},
{id:'54', cat:[{catID:'9'}], name:'Travel Bag', link: '/gloveThumbs/54.jpg'},
{id:'55', cat:[{catID:'9'}], name:'Back Pack', link: '/gloveThumbs/55.jpg'},
{id:'56', cat:[{catID:'9'}], name:'Lanyard', link: '/gloveThumbs/56.jpg'},
{id:'57', cat:[{catID:'9'}], name:'Stickers', link: '/gloveThumbs/57.jpg'},
{id:'58', cat:[{catID:'9'}], name:'Vinyl Track Banners', link: '/gloveThumbs/58.jpg'},
{id:'59', cat:[{catID:'9'}], name:'Umbrella', link: '/gloveThumbs/59.jpg'},
{id:'60', cat:[{catID:'9'}], name:'Raincoat', link: '/gloveThumbs/60.jpg'},
{id:'61', cat:[{catID:'9'}], name:'Logo Hat', link: '/gloveThumbs/61.jpg'},
{id:'62', cat:[{catID:'9'}], name:'Scatter Hat', link: '/gloveThumbs/62.jpg'},
{id:'63', cat:[{catID:'6'}], name:'TAA FastFit® Glove', link: '/gloveThumbs/63.jpg'},
{id:'64', cat:[{catID:'6'}], name:'TAA Original® Glove', link: '/gloveThumbs/64.jpg'},
{id:'65', cat:[{catID:'6'}], name:'TAA M-Pact® Glove', link: '/gloveThumbs/65.jpg'},
{id:'66', cat:[{catID:'6'}], name:'TAA M-Pact® 2 Glove', link: '/gloveThumbs/66.jpg'},
{id:'67', cat:[{catID:'6'}], name:'TAA M-Pact® 3 Glove', link: '/gloveThumbs/67.jpg'},
{id:'68', cat:[{catID:'9'}], name:'20 Year T-Shirt', link: '/gloveThumbs/68.jpg'},
]};